### ISSUE TITLE
6 logos pour le programme Weini 

### ISSUE THREAD

**Issue by yellow-panther** [tryingsomestuff/Weini#1]
Salut Vivien,
le mot Weini n´existe pas dans la langue allemande, (au contraire: Wein~ vin, weinig~vineux /vineuse)
J´ai ajoute un fichier avec le logicel graduit  http://photofiltre.free.fr/ ici:
[logos bitmap.zip](https://github.com/tryingsomestuff/Weini/files/2292620/logos.bitmap.zip)

On peut utiliser ces logos avec les cadres comme Arena, ChessGUI ou WinBoard.
http://computer-chess.org/doku.php?id=computer_chess:wiki:lists:gui_protocol_support_list

**Comment by tryingsomestuff** [comment]
Merci mais j'ai déjà un logo ;-)
